#pragma once

#include <cstdint>

#include "BackgroundTileData0.hpp"
#include "BackgroundTileData1.hpp"

// Auto-generated by convert_art.py — do not edit.
// Source: background2.png  cropped to 320×224 px
// 40 tiles wide × 28 tiles tall = 1120 tiles total.

namespace BG {

static constexpr int TILE_W     = 40;
static constexpr int TILE_H     = 28;
static constexpr int TILE_COUNT = 1120;
static constexpr int HALF       = 560;

// 16 CRAM entries (0000_BBB0_GGG0_RRR0)
inline constexpr uint16_t palette[16] = {
    0x06AC, // index 0
    0x0846, // index 1
    0x044A, // index 2
    0x0624, // index 3
    0x0624, // index 4
    0x0424, // index 5
    0x0422, // index 6
    0x0402, // index 7
    0x0402, // index 8
    0x0402, // index 9
    0x0402, // index 10
    0x0202, // index 11
    0x0200, // index 12
    0x0000, // index 13
    0x0000, // index 14
    0x0000, // index 15
};

} // namespace BG
