"""Projectile ``Information`` tokens.

``Projectile`` is a direct observation, built by ``observe.py`` in this
package. ``IncomingProjectile`` is an inference output, constructed by
``inference.py`` from ``Projectile`` tokens; it lives here only because
``inference.py`` imports the shape from this module.
"""

from __future__ import annotations

from abc import ABC
from dataclasses import dataclass

from .tokens import Inferred, Observed


@dataclass(frozen=True, slots=True, kw_only=True)
class Projectile(Observed):
    """Direct observation of a live projectile-kind object in flight."""

    slot: str
    world_x: int
    world_y: int
    vel_x: float
    vel_z: float


@dataclass(frozen=True, slots=True, kw_only=True)
class IncomingProjectile(Inferred):
    """A ``Projectile`` judged to threaten a playable character.

    Generated by ``check_for_incoming_projectiles`` (via
    ``generate_inference_tokens``) when a ``Projectile`` sits in the actor's
    lane, is heading toward it, and is within the time-to-impact window.
    """

    slot: str
    world_x: int
    world_y: int
    vel_x: float
    vel_z: float


@dataclass(frozen=True, slots=True, kw_only=True)
class StageObjects(Observed, ABC):
    """An inanimate object placed in the stage, observed directly from RAM."""


@dataclass(frozen=True, slots=True, kw_only=True)
class Pit(StageObjects):
    """A floor gap (pit) the player can fall into.

    Observed from ``GameSnapshot.floor_holes`` (the ``hazards.py``
    collision-class scan); fields mirror ``FloorHole`` — an AABB of the
    open region, ``lane_y`` being the top lane in pixels.
    """

    world_x: int
    lane_y: int
    width: int
    height: int


@dataclass(frozen=True, slots=True, kw_only=True)
class SafeSpot(Inferred):
    """A nearby point the actor can back off to that is clear of trouble.

    Produced by ``inference.check_for_safe_spots`` only while the actor has
    an ``IncomingMelee`` to back away from: the best of a small set of
    candidate steps around it, keeping the one that is furthest from every
    live enemy while staying inside the playable lane and the camera, and
    off any ``Pit`` (plus ``reach.PIT_AVOID_MARGIN`` of clearance). Absent
    when no candidate qualifies -- retreating then falls back to stepping
    straight away on X.
    """

    actor_slot: str
    world_x: int
    world_y: int


@dataclass(frozen=True, slots=True, kw_only=True)
class Breakable(StageObjects):
    """Intact smashable prop (phone booth, crate, …) — punch to break.

    Observed from map entities with ``kind == "breakable"`` that are still
    intact (not debris). Blocks lateral progress until destroyed.
    """

    slot: str
    world_x: int
    world_y: int
    type_id: int
